name: 'Bump CDK'
description: 'Action for creating pull requests to bump aws cdk dependencies'
author: cdk-tools
inputs:
  github-token:
    description: the github auth token
    required: true
  branch:
    description: the branch to commit to
    required: false
  working-directory:
    description: 'Sets the working directory'
    required: false
  version:
    description: 'Explicit version to set cdk dependencies to'
    required: false
  debug:
    description: 'Sets debug mode'
    required: false
outputs:
  version:
    description: 'The version of CDK that the project has been set to'
  pullNumber:
    description: the pull request number
  commitSha:
    description: the sha of the commit
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: activity
  color: green
